// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Custom type for trigger return (PostgreSQL trigger function)
export type trigger = Record<string, never>;

export type subscription_tier = 'free' | 'starter' | 'pro' | 'enterprise'
export type testimonial_status = 'draft' | 'pending' | 'approved' | 'published' | 'archived'
export type video_status = 'processing' | 'ready' | 'failed' | 'deleted'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          company_name: string | null
          website: string | null
          subscription_tier: subscription_tier
          stripe_customer_id: string | null
          subscription_id: string | null
          monthly_video_limit: number
          videos_used_this_month: number
          storage_used_bytes: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          company_name?: string | null
          website?: string | null
          subscription_tier?: subscription_tier
          stripe_customer_id?: string | null
          subscription_id?: string | null
          monthly_video_limit?: number
          videos_used_this_month?: number
          storage_used_bytes?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          company_name?: string | null
          website?: string | null
          subscription_tier?: subscription_tier
          stripe_customer_id?: string | null
          subscription_id?: string | null
          monthly_video_limit?: number
          videos_used_this_month?: number
          storage_used_bytes?: number
          created_at?: string
          updated_at?: string
        }
      }
      campaigns: {
        Row: {
          id: string
          user_id: string
          name: string
          slug: string
          description: string | null
          questions: Json
          theme_color: string
          logo_url: string | null
          is_public: boolean
          allow_anonymous: boolean
          notify_on_submit: boolean
          redirect_url: string | null
          total_views: number
          total_submissions: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          slug: string
          description?: string | null
          questions?: Json
          theme_color?: string
          logo_url?: string | null
          is_public?: boolean
          allow_anonymous?: boolean
          notify_on_submit?: boolean
          redirect_url?: string | null
          total_views?: number
          total_submissions?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          slug?: string
          description?: string | null
          questions?: Json
          theme_color?: string
          logo_url?: string | null
          is_public?: boolean
          allow_anonymous?: boolean
          notify_on_submit?: boolean
          redirect_url?: string | null
          total_views?: number
          total_submissions?: number
          created_at?: string
          updated_at?: string
        }
      }
      testimonials: {
        Row: {
          id: string
          campaign_id: string
          author_name: string
          author_email: string | null
          author_company: string | null
          author_role: string | null
          author_avatar_url: string | null
          content: string
          rating: number | null
          video_asset_id: string | null
          status: testimonial_status
          is_featured: boolean
          ip_address: string | null
          user_agent: string | null
          referrer: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          campaign_id: string
          author_name: string
          author_email?: string | null
          author_company?: string | null
          author_role?: string | null
          author_avatar_url?: string | null
          content: string
          rating?: number | null
          video_asset_id?: string | null
          status?: testimonial_status
          is_featured?: boolean
          ip_address?: string | null
          user_agent?: string | null
          referrer?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          campaign_id?: string
          author_name?: string
          author_email?: string | null
          author_company?: string | null
          author_role?: string | null
          author_avatar_url?: string | null
          content?: string
          rating?: number | null
          video_asset_id?: string | null
          status?: testimonial_status
          is_featured?: boolean
          ip_address?: string | null
          user_agent?: string | null
          referrer?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      video_assets: {
        Row: {
          id: string
          user_id: string
          campaign_id: string | null
          bucket_id: string
          storage_path: string
          original_name: string
          file_size: number | null
          mime_type: string | null
          status: video_status
          duration_seconds: number | null
          width: number | null
          height: number | null
          thumbnail_url: string | null
          signed_url_expires_at: string | null
          transcript: string | null
          thumbnail_generated: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          campaign_id?: string | null
          bucket_id?: string
          storage_path: string
          original_name: string
          file_size?: number | null
          mime_type?: string | null
          status?: video_status
          duration_seconds?: number | null
          width?: number | null
          height?: number | null
          thumbnail_url?: string | null
          signed_url_expires_at?: string | null
          transcript?: string | null
          thumbnail_generated?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          campaign_id?: string | null
          bucket_id?: string
          storage_path?: string
          original_name?: string
          file_size?: number | null
          mime_type?: string | null
          status?: video_status
          duration_seconds?: number | null
          width?: number | null
          height?: number | null
          thumbnail_url?: string | null
          signed_url_expires_at?: string | null
          transcript?: string | null
          thumbnail_generated?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      webhook_logs: {
        Row: {
          id: string
          source: string
          event_type: string
          payload: Json | null
          processed: boolean
          error_message: string | null
          created_at: string
        }
        Insert: {
          id?: string
          source: string
          event_type: string
          payload?: Json | null
          processed?: boolean
          error_message?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          source?: string
          event_type?: string
          payload?: Json | null
          processed?: boolean
          error_message?: string | null
          created_at?: string
        }
      }
    }
    Views: {}
    Functions: {
      is_campaign_owner: {
        Args: {
          p_user_id: string
          p_campaign_id: string
        }
        Returns: boolean
      }
      can_upload_video: {
        Args: {
          p_user_id: string
        }
        Returns: boolean
      }
      handle_new_user: {
        Args: Record<string, never>
        Returns: trigger
      }
    }
    Enums: {
      subscription_tier: subscription_tier
      testimonial_status: testimonial_status
      video_status: video_status
    }
  }
}
